### ISSUE TITLE
Issue on deployment

### ISSUE THREAD

**Issue by PetitCedric** [MagicDevilZhang/prometheus-kudu-exporter#1]
Hi,

I'm facing issue on initial configuration.

2022-05-24 13:45:59: WARN ForkJoinPool-1-worker-15 [KuduMetricRestFetcher.java: 91] - fetch kudu metric from RestAPI failed .
java.net.SocketException: Unexpected end of file from server
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851) ~[?:1.8.0_232]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_232]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848) ~[?:1.8.0_232]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_232]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) ~[?:1.8.0_232]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_232]
        at io.prometheus.kudu.fetcher.KuduMetricRestFetcher.process(KuduMetricRestFetcher.java:86) [prometheus-kudu-exporter-0.2.0.jar:?]
        at io.prometheus.kudu.task.KuduExporterTask.run(KuduExporterTask.java:75) [prometheus-kudu-exporter-0.2.0.jar:?]
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_232]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_232]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_232]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_232]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_232]

It seems to not work properly with https. Is it possible ?

# Fetcher Configuration
# Port of Kudu Server should be 8051, and Kudu Tablet Server should be 8050
prom.kudu.fetcher.classname: io.prometheus.kudu.fetcher.KuduMetricRestFetcher
prom.kudu.fetcher.kudu-nodes: [ ip1:8051, ip2:8050 ]
prom.kudu.fetcher.interval: 10000

# Standalone Reporter Configuration
# Please visit http://localhost:9055/metrics to check kudu-exporter status after start
prom.kudu.reporter.classname: io.prometheus.kudu.reporter.KuduMetricLocalReporter
prom.kudu.reporter.local.port: 9055

# Push-Gateway Reporter Configuration
# Push-Gateway should be install before running kudu-exporter
#prom.kudu.reporter.classname: io.prometheus.kudu.reporter.KuduMetricPushGatewayReporter
#prom.kudu.reporter.pushgateway.host: 127.0.0.1:9091
#prom.kudu.reporter.pushgateway.interval: 10000

**Comment by leeeizhang** [comment]
Kudu-exporter needs to crawl metrics via web API periodically. I think the problem happens in the crawling.


You may need to check whether the kudu web API is available at first:
```shell
curl -get http://ip1:8051/metrics?compact=1
```

Kudu-exporter only uses `http` to crawl metrics, and if your server has security restrictions or disabled the `http`, you may need to change the crawl site as `https://...`  in [io.prometheus.kudu.fetcher.KuduMetricRestFetcher [line. 68]](https://github.com/MagicDevilZhang/prometheus-kudu-exporter/blob/master/src/main/java/io/prometheus/kudu/fetcher/KuduMetricRestFetcher.java#L68). And maybe you need to supply some header configuration for HTTP requests.

Then, recompile the projects for testing:
```shell
# Install Git and Maven
$ sudo apt-get update
$ sudo apt install git maven

# Compile by Maven
$ sudo mvn clean package
```


Hope my advice will help you. Any further questions are welcome for posting!

**Comment by PetitCedric** [comment]
Hello,

I finally have the curl working. I indeed need to use https because http is prohibited.
Futhermore, we're using Kerberos so it needs to be a https SPNEGO authentication.

For the curl, this one works :

curl -get https://user:pwd@IP1:8051/metrics?compact=1 --cacert /var/lib/cloudera-scm-agent/agent-cert/cm-auto-global_cacerts.pem --negotiate

I'm not developer but i'll try to adapt your code. If i finally get something working, i'll keep you posted in case you are interested to add the https/spnego feature

Thanks and have a nice day

**Comment by leeeizhang** [comment]
Thank you for your suggestion. I will consider adding security certification in the near future. 👨‍💻
